[package]
name = "xwlm"
version = "0.2.0"
edition = "2024"

[dependencies]
wlx_monitors = { path = "../wlx_monitors" }
ratatui = "0.30.0"
serde = { version = "1", features = ["derive"] }
toml = "1.0.3"
thiserror = "2.0.18"
crossterm = "0.29.0"
